import { NgModule } from '@angular/core';
import { MatFormFieldModule } from '@angular/material';
import {
  MatIconModule,
  MatLabel,
  MatHint,
  MatInput,
  MatInputModule,
  MatSuffix,
  MatCardModule,
  MatButtonModule,
  MatStepperModule,
  MatStep,
  MatStepperPrevious,
  MatStepLabel,
  MatStepperIcon,
  MatStepperNext,
  MatHorizontalStepper,
  MatSelect,
  MatOption,
  MatSelectModule,
  MatRadioModule,
  MatListModule,
  MatDialogModule,
  MatDialog,
  MatDialogRef,
  MAT_DIALOG_DATA,
  MatExpansionModule,
  MatAccordion,
  MatNativeDateModule,
  MatDatepickerModule,
  MatProgressSpinnerModule,
  MatTableModule,
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatStepperModule,
  MatSelectModule,
  MatRadioModule,
  MatListModule,
  MatDialogModule,
  MatExpansionModule,
  MatNativeDateModule,
  MatDatepickerModule,
  MatProgressSpinnerModule,
  MatTableModule,
  ],
  exports: [
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatStepperModule,
  MatSelectModule,
  MatRadioModule,
  MatListModule,
  MatDialogModule,
  MatExpansionModule,
  MatNativeDateModule,
  MatDatepickerModule,
  MatProgressSpinnerModule,
  MatTableModule,
  ],
  })
export class MaterialImportsModule {}
